version: '3'
services:

  ## API ##
  api-wallet:
    build:
      context: .
      dockerfile: Dockerfile
    #image: dowglasmaia/wallet-service-api:v4
    container_name: wallet-service-api
    ports:
      - "8001:8001"
    networks:
      - maianet
      - broker-kafka
    environment:
      - DOTEL_SERVICE_NAME=address-api
      - DOTEL_TRACES_EXPORTER=otlp
      - DOTEL_METRICS_EXPORTER=none
      - DOTEL_EXPORTER_OTLP_ENDPOINT=http://collector-api:4318
      - DOTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf


  audit-service-api:
    image: dowglasmaia/audit-service-api:v3
    container_name: audit-service-api
    networks:
      - maianet
      - broker-kafka
    ports:
      - "8002:8002"
    depends_on:
      - kafka
      - mongo

  pg-db:
    container_name: pg-db
    image: postgres:14.12-alpine3.18
    networks:
      - maianet
    environment:
      - POSTGRES_USER=maia
      - POSTGRES_PASSWORD=maiapw
      - POSTGRES_DB=walletDB
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  ## MONGO ##
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - maianet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    volumes:
      - mongo_data:/data/db
    networks:
      - maianet

## KAFKA ###
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Porta acessível do host
      - "29092:29092"  # Porta para comunicação interna entre contêineres
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092


## OBSERVABILITY ##
  collector-api:
    image: otel/opentelemetry-collector:latest
    container_name: collector-api
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - 4317:4317
      - 4318:4318
    networks:
      - maianet

  jaeger-api:
    image: jaegertracing/opentelemetry-all-in-one
    container_name: jaeger-api
    ports:
      - 16686:16686
    networks:
      - maianet
    depends_on:
      - collector-api

## SONAR ##
  sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - db-sonar
    networks:
      - maianet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db-sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs

  db-sonar:
    image: postgres:14.12-alpine3.18
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - maianet
    volumes:
      - sonar_db:/var/lib/postgresql

networks:
  maianet:
  broker-kafka:
    driver: bridge


volumes:
  postgresql:
  postgresql_data:
  prometheus_data:
  mongo_data:
  sonar_data:
  sonar_logs:
  sonar_db: