spring:
  application:
    name: wallet-service

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      client-id: admin

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/walletDB
    username: maia
    password: maiapw
    pool:
      max-size: 20  # Número máximo de conexões simultâneas
      initial-size: 10  # Número inicial de conexões
      max-idle-time: 30s  # Tempo máximo de ociosidade antes de uma conexão ser fechada
      max-create-connection-time: 5s  # Tempo máximo para criar uma nova conexão

  jackson:
    default-property-inclusion: NON_NULL

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    tags:
      application: address-api
    distribution:
      slo:
        http: '5ms,10ms,25ms,50ms,100ms,200ms,300ms,400ms,500ms,1s,2s'
      percentiles-histogram:
        http:
          server:
            requests: true


logging:
  file:
    name: logs/wallet-service.log
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

server:
  port: 8001

info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'

