spring:
  application:
    name: wallet-service

  kafka:
    bootstrap-servers: localhost:9092
    admin:
      client-id: admin

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/walletDB
    username: maia
    password: maiapw
    pool:
      max-size: 20  # Número máximo de conexões simultâneas
      initial-size: 10  # Número inicial de conexões
      max-idle-time: 30s  # Tempo máximo de ociosidade antes de uma conexão ser fechada
      max-create-connection-time: 5s  # Tempo máximo para criar uma nova conexão

  jackson:
    default-property-inclusion: NON_NULL


logging:
  file:
    name: logs/wallet-service.log
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

server:
  port: 8001
